### ISSUE TITLE
[infinite scroll] duplicates returned

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#108]
Screenshot comes from memefolio, but all other lists are probably affected too. When scrolling past initial loaded number (currently 5) `::gql/query` (with an id returns) duplicated entries. 
![scrolling_duplicates](https://user-images.githubusercontent.com/468572/53348777-ff33dd00-391b-11e9-980e-c74a7f25635c.jpg)

**Comment by fbielejec** [comment]
Most likely a bug in https://github.com/district0x/district-ui-graphql

**Comment by jpmonettas** [comment]
@fbielejec I haven't seen that in a while, are you able to consistently reproduce that?

**Comment by fbielejec** [comment]
Every time, yes.

**Comment by jpmonettas** [comment]
@fbielejec I haven't look at the code yet but since I haven't seen that in a long time and I saw some pull request that was changing query ids, I'm pretty sure it is related to that. If you re do some query but don't include the parameters in the id, it will accumulate results, since id doesn't change

**Comment by fbielejec** [comment]
Still present on dank-registry page ![2019-03-01-1551448380_screenshot_3286x1080](https://user-images.githubusercontent.com/468572/53642428-0ae01600-3c32-11e9-847b-845ea8125068.jpg)
