### ISSUE TITLE
[QA] The sales pitch section is going  to be a spam issue.

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#135]
We will have advertising and URL's in here if we don't block URLs or something that screens for these. Possibly even allow the community to flag Memes/addresses on the market that are an issue or spammy. 

Not sure best solution but this will be exploited I'm sure. This is a heavy conversation because the meme may be part of a game or something. URLs may be kinda cool in some respects if a third party game was made.

**Comment by Bradymck** [comment]
A simple 'Report' button may be solution.

**Comment by madvas** [comment]
I don't think this is gonna be too serious issue, since to see sales pitch one has to turn card manually, which makes it not so ideal as ad space. Also, we don't convert URLs into links, which makes it even less attractive for spammers. So I'd say, for MVP we leave it without protection, if things go wrong, we'll apply countermeasures.

**Comment by Bradymck** [comment]
Okay sounds good to me. Closing this out
