### ISSUE TITLE
Display issue when starting sale

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#189]
When starting a sale, after populating the above fields and moving your cursor to the 'Short sales pitch' field, red text appears behind the 'Cancel' button. Not sure what the text says, but it should either be made visible if its something we want people to see, or be removed. 

Also, the Cancel button remains dulled/greyed out regardless of what fields have been populated. It should be fully colorized regardless of what fields have been filled if any.

See attached screenshot
<img width="396" alt="Screen Shot 2019-03-13 at 11 58 11 AM" src="https://user-images.githubusercontent.com/16138359/54307164-38a95100-4588-11e9-8478-6a99fe437ae2.png">

**Comment by jpmonettas** [comment]
@joeyurgz that text says description should not be empty. That bug was introduced when we added "Send tokens" since I didn't took into account space for that. Will be tricky where to get that space from. 
@madvas should we remove the description error message?

Cancel button is that color by design, is not greyed out, so maybe talk to the designers about it?

**Comment by madvas** [comment]
Sales pitch can be empty, error text is not needed
