### ISSUE TITLE
Website Guide

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#256]
@Alexand0x you can start to preparing story for website guide. What I imagine is that, we'll just guide the user through certain pages, explaining briefly what the page is all about, rather than requiring user to do some advanced actions, such as buying or challenging a meme. Basically, no action requiring sending a transaction should be required to do, it may be suggested, but there will be always skip button offered and guide can continue without that action being done. 

It may go somewhat like this: 
(So you can better imagine, take a look at this demo of library, which we'll probably use http://xbsoftware.github.io/enjoyhint/ )

1. Screen is dimmed, only Marketplace menu item is highlighted, with arrow pointing to it, saying: _"Let's take a look at Marketplace, where all good memes are traded!"_
2. First card in offered on marketplace gets highlighted, guide saying: _"Flip the card by clicking on it, to display more information"_
3. After user flips the card, buy button gets highlighted, guide saying: _"If you like this meme, you can press Buy button, which will initiate Ethereum transaction that will make you provable owner of this meme!"_ Skip button will be offered. 
...
... 
And so on...

You may want to collab with other operations guys to decide, which pages and actions should be included in guide, so it's neither too long or too brief.

**Comment by Alexand0x** [comment]
We should link the user in from somewhere else, or prompt them to start the tutorial. We shouldn't display it to all first time users by default, users should know they're entering a tutorial.

The other big concern is what happens if there is no current vote/challenge object to point a user towards. For this same reason, we can't really explain much on the Memefolio page (such as selling a meme).

---------------------------------------------
1. Screen is dimmed. Marketplace menu item is highlighted.
"At it's core, Meme Factory is a decentralized marketplace for collectible memes."

2. User navigates to marketplace. Middle meme is highlighted. Arrow points to meme card itself.
Above meme: "Memes exist as provably rare tokens on the blockchain, and work a lot like digital trading cards." 

Next to arrow: "Click to flip over!"

3. User clicks meme. Meme flips, and is still highlighted.
"Memes are minted, auctioned, and sold on Meme Factory for Ethereum. Each meme has a fixed supply, and is provably rare. Once issued, no more will ever be made, and only the original supply can be traded and re-traded."

4. User clicks "next" or something of the sort. Now, just the buy button on the card is lit.
"If you find a meme you like listed for sale, simply click the buy button then submit and confirm the Ethereum transaction. Once purchased memes are yours to keep, sell, move, or trade away forever."

5. User clicks "next" or "skip". My Memefolio gets highlighted, with an arrow.

"Any memes you own will appear in your Memefolio."

6. User clicks "My Memefolio". The search function and their meme collection (entire middle portion of the app) is highlighted. Text above says:
"Your Memefolio contains your current collection of memes as well as a complete history of memes you've bought and sold."

7. User clicks "Next". Only the line of tabs is highlighted. Text below reads:
"Meme Factory gives you the power not only to buy and sell on the marketplace, but control what enters the marketplace. You can _create_ memes, and these memes are _curated_ through a process of challenges and votes. 

8. User clicks "Next". The "Get DANK" menu item is highlighted, with arrow. Text reads.
"In order to start curating, you need a special token for the job, called DANK."

9. User clicks "Get DANK". Faucet module is highlighted. Below is the text:
"This page offers a one-time allotment of DANK tokens to get you started. It requires a phone number to prevent abuse. Don't worry - we'll show you how to earn more DANK next."

10. User clicks "Next". The "Vote" option in the menu is highlighted. An arrow points to it. Next to it is the text:
"Once you've acquired some DANK, we can get started voting."

11. User clicks "Vote". The vote page loads with tabs, sorting, and top challenge area highlighted. Text reads:
"This page shows all open challenges against new meme submissions. When a challenge is initiated, a period of voting begins. Any DANK you own can be used as voting power to decide whether a new meme goes to auction or gets rejected."

12. User clicks "Next". The left side of the meme gets highlighted.

"To the left, you can see all of the details of the creation of this meme, as well as the stated reason for the challenge. You can also see the success rates of the creator and challenger in their respective roles."

13. User clicks "Next". The voting options STANK/DANK to the right of the card are highlighted.

"Voting is simple. To the right, you can choose the amount of voting power you want to assign to "DANK" or "STANK". Your tokens will be returned to you in full, and if you're on the winning side, you'll even get a bit extra. So you should always be trying to vote with your DANK to earn more."

14. User clicks "Next" or "Skip". The right side of meme stays highlighted, but we also highlight the time left line on the left of meme.

"When the voting period ends, you must return to this challenge and _reveal_ your vote in order to make it public. This prevents any sort of influence from earlier votes. Just press the "reveal" button to the left of any meme you've voted on during the reveal period."

15. User clicks "Next" or "Skip". The "Resolved Challenges" tab is highlighted, and the "My Memefolio" menu button is highlighted.

Near Tab: "After the reveal period ends, the challenge moves to the resolved tab. Any rewards from winning votes or challenges can be claimed here."

Near Menu: "Also note that you can reveal votes and claim rewards at any time via the "Curated" tab of the "My Memefolio" page."

16. User clicks "Next" or "Skip". The "Challenge" menu item is highlighted. 

"Starting a challenge is also easy. Keep in mind however, unlike voting, you can actually lose DANK while challenging. To get started, press the "Challenge" button."

17. User clicks the "Challenge" menu item. The top challenge item in the list is highlighted. 

"This page displays every new meme submitted for entry into the registry. All memes must survive a challenge period to make it into the registry uncontested. If challenged, memes will go to the voting phase."

18. User clicks "Next". The "Challenge" button is highlighted, along with the challenge period timer.

"At any point during the challenge period, you may challenge a meme you don't like by matching and risking the DANK the meme creator used to submit the meme."

19. User clicks "Challenge" or "Skip". The "Vote" and "My Memefolio" menu button are highlighted.

"New challenges move to the vote page. When voting concludes, rewards from complete challenges can be claimed from the "Resolved Challenges" tab on the vote page, or in your Memefolio."

20. User clicks "Next". The "Submit" menu button is highlighted.

"The final major feature of Meme Factory is, of course, creating memes. This is done with DANK on the "Submit" page."

21. User clicks "Submit". The left module (upload) is highlighted.

"To create a meme, find or create an appropriate image file. It's important to submit a meme with a vertical 2:3 aspect ratio, and less than 1.5MB. Most common image formats are accepted. If you need tips for creating memes, click [REDIRECT TO MEME CREATION GUIDE]"

22. User clicks "Next" or "Skip". The right module (meta-data) is highlighted.

"Submissions require names, and tags to index them for searching. Be creative, but also descriptive here. You must also choose a number of individual cards to mint and issue for sale. You can leave a comment to provide any other information you think challengers or voters might need."

23. User clicks "Next". The "Challenge" and "Memefolio" menu items are highlighted.

"Memes that are submitted move to the Challenge phase. Any creations of yours can always be found in the "Created" tab of the "My Memefolio" page", where you can issue accepted memes for sale.

24. User clicks "Next". The "My Settings" menu item is highlighted.

"The settings page allows you to link your email address in order to sign up for notifications. This will provide updates on any memes you've created, challenged, or voted for."

25. User clicks "Next" or "My Settings". The "How it Works" page is highlighted.

"Any additional questions are likely answered in our "How it works" walkthrough. Welcome to Meme Factory!"
--------------------------------------

I did my best to cut it down to fewer steps, but the more steps i cut, the more dense each step becomes (e.g. on submit a meme page, could highlight each field individually and explain, or do them all at once with more text). Would like to test and feel this out to know what's the correct way to go.

**Comment by madvas** [comment]
This is dope, thank you! 
> We should link the user in from somewhere else, or prompt them to start the tutorial. We shouldn't display it to all first time users by default, users should know they're entering a tutorial.

Yes, we're gonna have following button to start the tutorial 
![image](https://user-images.githubusercontent.com/3857155/55453421-02e70d80-5606-11e9-99e7-ec5d8c237693.png)

> The other big concern is what happens if there is no current vote/challenge object to point a user towards. For this same reason, we can't really explain much on the Memefolio page (such as selling a meme).
I wouldn't be too concerned about this, since challenge/voting period in production will be much longer than currently on QA. Probably will be around 1 day, so I'm quite positive there's always gonna be something.

**Comment by madvas** [comment]
So, this is good to go for implementation. Here's [button icon](https://github.com/district0x/memefactory/files/3039023/guide-me-button-icon.svg.zip). Color is `:purple`. Button should be displayed only for devices with `:large` screen and higher.

**Comment by jpmonettas** [comment]
@Alexand0x @madvas there are a couple of things there that doesn't seem to be possible using this library, so far :
- highlight two parts at the same time
- add more than one piece of text to a step

I'm listing this since they are part of requirements

**Comment by jpmonettas** [comment]
Other thing I found enjoyhint doesn't handle well is when the step selector doesn't find the element it is supposed to highlight, it just throws a error and stops the tutorial. This can be problematic since we are assuming that some elements are going to be there (memes in marketplace, challenges and votes) but maybe not. 
Maybe we can fork the project and do something about it.

**Comment by madvas** [comment]
Catching the error is not possible?

**Comment by jpmonettas** [comment]
@madvas All you give to the library is a collection of steps, together with some configuration options, so no per step code where you can catch anything. (At least not easy to see from the doc)

**Comment by madvas** [comment]
These 3 steps are not readable" 
![image](https://user-images.githubusercontent.com/3857155/56136056-2aea4f80-5fbc-11e9-9cf7-39b72ec8c5c5.png)

![image](https://user-images.githubusercontent.com/3857155/56136110-4c4b3b80-5fbc-11e9-8334-e5708a270df5.png)

![image](https://user-images.githubusercontent.com/3857155/56136153-62f19280-5fbc-11e9-9da1-d395c8c49ba3.png)

**Comment by madvas** [comment]
Some other issues: 
* Typo in button text. Should be "Guide me"
* Guide me button is clickable only when clicking on text. Should be able to click anywhere on the button
* No need to include cljsjs/jQuery. Easyhint comes with jquery included. 
* Include CasinoHand font, that's expected in easyhint.css https://github.com/xbsoftware/enjoyhint/tree/master/src
* When highlighting any menu item, please highlight the whole tab, not just text
![image](https://user-images.githubusercontent.com/3857155/56137151-60903800-5fbe-11e9-8803-83ff7054a1f5.png)
* The step when clicking on My Memefolio goes away too fast. Can it wait until clicking Next button? 
![tutorial-bug1](https://user-images.githubusercontent.com/3857155/56137482-2a9f8380-5fbf-11e9-8700-1d51f44b3342.gif)

**Comment by Alexand0x** [comment]
The card highlight doesn't overlay the top card for me on Marketplace step. It gets it correct before the Search/filter box loads in, then that loads in and the page jumps, and the highlight is off. 

![image](https://user-images.githubusercontent.com/29998350/56439119-05f32680-62b3-11e9-8162-92de4885a5e6.png)

The highlight continues to be a little bit off after pressing next a few times.
![image](https://user-images.githubusercontent.com/29998350/56439187-3f2b9680-62b3-11e9-896c-a5e5644a9d8f.png)

Step 5 where My Memefolio is highlighted displays the wrong text. Should say "Any memes you own will appear in your Memefolio."

In next step, Memefolio tab highlights are also off a tiny bit.
![image](https://user-images.githubusercontent.com/29998350/56439501-5028d780-62b4-11e9-8710-caf0bd34edb0.png)

After clicking "Get Dank" in step 8, the faucet page opens, but the same text remains.
![image](https://user-images.githubusercontent.com/29998350/56439370-c973fa80-62b3-11e9-8588-c9939cf08e60.png)

It then skips to step 10. Step 9 is never shown. Clicking on "Vote" stalls me at step 10. I can't click anything to get to Step 11 or beyond.

**Comment by madvas** [comment]
It happens sometimes to me also that highlight is not quite where it should be, but quitting tutorial and starting again usually helps. I don't know how often it happens to you, but to me not too often. This is not really error in our code, but in library's code.

**Comment by madvas** [comment]
yeah, tutorial gets stuck if it gets to voting page and there's nothing to vote about. Again, it's the library that's missing functionality to handle this. I don't expect this to be happening in production since challenge/voting periods will be much longer than on QA, I think there's always gonna be something in the list, but we'll see. Maybe we can come up with some workaround if this problem will be occurring in prod.

**Comment by Alexand0x** [comment]
Step 5 still has the wrong text. Says "At it's core" as in step 1, but should say

"Any memes you own will appear in your Memefolio."
