### ISSUE TITLE
Fix up the top right styling

### ISSUE THREAD

**Issue by benzap** [district0x/memefactory#281]
Feels like the styling on the top right which displays the dank and eth tokens could be centered a bit better

From this:
![this](https://i.imgur.com/BerJksR.png)

To something like this:
![that](https://i.imgur.com/SUZKsuT.png)

**Comment by madvas** [comment]
can be

**Comment by madvas** [comment]
Icons are too big @benzap, not like you've sent on the picture
![image](https://user-images.githubusercontent.com/3857155/55054156-551db100-5091-11e9-9637-be4fbedba63b.png)

**Comment by fbielejec** [comment]
I kinda like the bigger icons

**Comment by madvas** [comment]
It's bit too big now, besides space for ETH balance is disproportionally smaller than for DANK, makes it look weird. 
Also, since we're dealing with this, in designs there's separation line between the two 
![image](https://user-images.githubusercontent.com/3857155/55056585-125fd700-5099-11e9-84bf-e511088d449f.png)

**Comment by benzap** [comment]
Going to include the button submission change you suggested in the same PR, i'll post screenshots

**Comment by benzap** [comment]
fixed in #300 PR
