### ISSUE TITLE
Resolved Challenges results not visible when no active account

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#317]
When there's no active account, we're keeping whole right section of Resolved Challenges hidden. This is not necessary. Everything should be visible except: Reward buttons, "You voted...", "Your reward..."

![image](https://user-images.githubusercontent.com/3857155/55137162-d3965380-5162-11e9-80fc-7ee23540d54c.png)

**Comment by benzap** [comment]
Unassigned myself for now in case someone wants to take a stab at this. The fix will involve removing [this](https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/dank_registry/vote_page.cljs#L47) and changing the graphql resolver to generate a dataset for [this](https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/dank_registry/vote_page.cljs#L67), since it does not resolve due to the `nil` active-account
