### ISSUE TITLE
Related Memes scrolling needs more ❤️

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#397]
Following page gives somewhat weird behaviour when 6 cards are in a list. When scrolling to the bottom, last one sort of jumps into a new row. When scrolling back up, it gets normal again. 

If you cannot reproduce, try with different window sizes. 

http://qa.district0x.io/meme-detail/0x9c1907ac614f2f999f644085ddee4dcd67382c27

![related-infinite-scroll](https://user-images.githubusercontent.com/3857155/56296827-6ff7b880-6159-11e9-8d69-83f95308756a.gif)

Bonus points: 
Spinner is not centred
![image](https://user-images.githubusercontent.com/3857155/56297100-ebf20080-6159-11e9-9f4f-8403a736b544.png)

**Comment by jpmonettas** [comment]
We decided to remove infinite scrolling from related memes and just show first 16.
Cause: 
I'm almost sure react-infinite doesn't support this use case, things are disappearing because react-infinite not only adds elements to the bottom but it also removes from the top, so you can get a real infinite scroll without creating a infinite big page
For this to work correctly, the relation sizes between container height and element height should be correct but when we use the entire window as scroll container, we have lot of extra things in the same page

**Comment by fbielejec** [comment]
There's a prop for controlling how many items get preloaded, maybe we can
try and tweak that value to get a decent behavior?
