### ISSUE TITLE
Email styling broken on mobile

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#430]
![Screenshot_20190506-193738](https://user-images.githubusercontent.com/468572/57243503-9614c800-7036-11e9-9efe-fb9b78490d60.jpg)

**Comment by benzap** [comment]
Unfortunately, this isn't an easy fix, since HTML in emails has to use old table styling layouts which are not responsive. One thing to consider is to stack those table cells as a column instead of a row, which will look better on mobile, but i'm not sure how it would look on desktop

**Comment by fbielejec** [comment]
Possible solution: Middle ground between desktop and mobile

**Comment by benzap** [comment]
Moved some styling around, this is what i've got:

Desktop:
![](https://i.imgur.com/tOBo4Yf.png)

Mobile: kind of grainy mobile mode in desktop browser. Tested on mobile, and has the same layout
![](https://i.imgur.com/F81i24n.png)

**Comment by benzap** [comment]
@madvas @fbielejec bump

**Comment by benzap** [comment]
Might be possible to move the unsubscribe button to the right of 'Part of the district0x Network', but i'm not sure how important this is

**Comment by madvas** [comment]
Could there be less vertical space between those:
![image](https://user-images.githubusercontent.com/3857155/61095546-106e2800-a47e-11e9-8313-42e1cf81839c.png)

**Comment by fbielejec** [comment]
Looks like a good middle-ground. There could be less space as per what @madvas wrote between first two, and some more significant spacing between that and __Unsubscribe__

**Comment by benzap** [comment]
@madvas @fbielejec 

I think reducing it makes sense too.

So I can reduce the height of each table row, but just so you're aware, each of those rows consists of a image that I will need to crop to an appropriate size, and host 'somewhere'. The table row height is pegged to the height of the images, which is why I can't make them smaller otherwise.

I brought this up last time I worked on the template at #428 

For a temporary fix, I can host the images at imgur, but it looks like the originals are being hosted elsewhere. Might need some insight into how to host the new images in the same place. Additionally, I could look into just replacing the images with actual text elements, but it might have been done this way due to a limitation.

**Comment by madvas** [comment]
ah I see, those are images. I think it's not worth the trouble at the moment. You can leave it as it is.

**Comment by fbielejec** [comment]
Images are hosted on sendgrid

**Comment by benzap** [comment]
@madvas I ended up fixing it:

# Desktop Preview
![](https://i.imgur.com/mLixvxv.png)

# Mobile Preview
![](https://i.imgur.com/yuoCTfB.png)

Thanks for the heads up @fbielejec, i'll start moving the images over to be hosted by sendgrid if that's the case.

**Comment by benzap** [comment]
@madvas @fbielejec image urls are not being hosted correctly 👍

**Comment by fbielejec** [comment]
Is it a typo error? If not what do you mean by not correctly?

**Comment by benzap** [comment]
I fixed it 10 seconds after I posted it @fbielejec 😃
