### ISSUE TITLE
[Infinite Scroll] Scrolling Mobile Experience on Challenges Vote page Improvement

### ISSUE THREAD

**Issue by benzap** [district0x/memefactory#477]
Scrolling while on mobile within the Open Challenges is erratic when scrolling. I keep getting bumped back up in a strong-armed manner, which makes the whole experience unpleasant, since it continues to manifest when I try and scroll back up to view the challenge that was passed as a result of the scroll bumping.

Possible fixes might involve different height constraints [here](https://github.com/district0x/memefactory/blob/master/src/memefactory/ui/components/challenge_list.cljs#L186)

Tested with Android on Brave(Chrome)

**Comment by madvas** [comment]
Improvement was pushed here https://github.com/district0x/memefactory/commit/27277626457202b21a8f836cce85cf5ab828dab9. Works quite well, but still not perfect, since height is changes little bit depending if for example it's in reveal period, or if nobody voted, there's no chart displayed. In order to be perfect we'd have to style each item with fixed height. May be done in future, but closing for now, as it's good enough.
