### ISSUE TITLE
Tags input should break lines

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#483]
When entering many tags, they should go underneath each other. 

![image](https://user-images.githubusercontent.com/3857155/57996435-a4acb600-7af1-11e9-8479-2075e50b2ca7.png)

**Comment by Bradymck** [comment]
When adding tags in Registry and Marketplace search fields, each tag adds a line break after every tag rather than at the end of the field.
![bug line break](https://user-images.githubusercontent.com/4667076/61151117-62c14000-a4a2-11e9-9b28-12481d31fd27.PNG)
![bug linebreak 2](https://user-images.githubusercontent.com/4667076/61151119-6654c700-a4a2-11e9-866e-02dbabc93863.PNG)

It should look like the fixed submit page seen below: 
![linebreak](https://user-images.githubusercontent.com/4667076/61151155-78cf0080-a4a2-11e9-8ff8-6504bef3c298.PNG)

Reopening issue
