### ISSUE TITLE
Memoize timestamp fetching in syncer

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#509]
Following line contributes to slowness of syncing. 

https://github.com/district0x/memefactory/blob/fc30420e1297c015fb69a3cf1cccca4667c5c7ea/src/memefactory/server/syncer.cljs#L373

Use clojure's [memoize](https://clojuredocs.org/clojure.core/memoize) function for caching timestamp for particular block number. In MF there's many events with the same block number, because many cards are transferred at once.

**Comment by fbielejec** [comment]
There is a lot more potential for speeding up the first and subsequent syncs:

- bulk transactions instead of `for` or `doseq`
- using upserts instead of `if-exists-update-else-insert` pattern

I suggest not overloading the syncer PR with these changes, instead I will address it in a separate issue.

**Comment by madvas** [comment]
hmm, I don't think those 2 points will have any noticeable effect on in-memory db, but can try
