### ISSUE TITLE
Events arrive out-of-order when resyncing past events

### ISSUE THREAD

**Issue by fbielejec** [district0x/memefactory#55]
Event replying does not guarantee order and can corrupt the data we store in the db (e.g. meme/buy arrives before meme/create)

**Comment by fbielejec** [comment]
Bug can be reproduced by calling `(generate-data)` and `(resync)` with ganache in auto-mining mode ( the default, no block time).

**Comment by DomKM** [comment]
Perhaps related: I was experiencing out-of-order event processing in District Registry but a simple queue in syncer.cljs fixed it. https://github.com/district0x/district-registry/blob/master/src/district_registry/server/syncer.cljs#L223-L288

**Comment by fbielejec** [comment]
closed with #644fcf15c82504363718777e17e4160e58155330

**Comment by jpmonettas** [comment]
> Perhaps related: I was experiencing out-of-order event processing in District Registry but a simple queue in syncer.cljs fixed it. https://github.com/district0x/district-registry/blob/master/src/district_registry/server/syncer.cljs#L223-L288

@DomKM I don't think this ensure proper event ordering. What it helps with is with not processing a new event until the one you are processing is fully finished (even when you go to ipfs in the middle)
The problem is that you add a bunch of filters to the ether node with callbacks to add them into the queue but you can't tell web3 to call your callbacks in any particular order.
