### ISSUE TITLE
p2p meme trading

### ISSUE THREAD

**Issue by MouyouMoos** [district0x/memefactory#674]
# Problem

I cant trade memes p2p with other people. I want to trade memes like cards on the schoolyard.

## Implementation

profile to browse memes from other people and request a trade. then s/he can look at my offer and accept it or check out my meme deck and make another offer.

**Comment by Alexand0x** [comment]
All of this is supported by the current marketplace and memefolio, with the exception of making offers on unlisted cards. Any memefolio attached to any ethereum address is available for public browsing, and if the trustless marketplace isn't peer-to-peer enough for your tastes, you can always send your ERC-721 tokens manually using any Ethereum wallet.

While offers are not directly supported, this kind of direct user interaction is something we'd prefer to support through community channels like discord - which is why we directly embedded the chat into our app.
